### ISSUE TITLE
Grammar mistakes in "About" section of the repository

### ISSUE THREAD

**Issue by vstraigis** [Jamtit/PSI-2022-GR3#4]
In the about section of this repository there are some grammar mistakes. "Respitory to for the"?.  It's repository, not respitory. Fix it please. "To for the" also, cmon.
![bruh](https://user-images.githubusercontent.com/97912354/199964505-7c6cace6-1630-4d83-a585-c2c7e95b1ee0.png)

**Comment by mindunas** [comment]
I agree

**Comment by Jamtit** [comment]
done
